/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireTextGoalLogEntry".
 */
export type WireTextGoalLogEntry = WireGoalLogEntry & {
  /**
   * Text content of the entry (TextGoalLogEntry.text in Dart)
   */
  te?: string | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WirePriorityLogEntry".
 */
export type WirePriorityLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: priority (PRIORITY_ENTRY_TYPE in Dart)
   */
  t: "p";
  /**
   * Priority value (PriorityLogEntry.priority in Dart)
   */
  pr?: number | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireNoteLogEntry".
 */
export type WireNoteLogEntry = WireTextGoalLogEntry & {
  /**
   * Entry type: note (NOTE_ENTRY_TYPE in Dart)
   */
  t: "n";
  /**
   * Id of the note entry being updated, if any (NoteLogEntry.updateNoteEntryId in Dart)
   */
  u?: string | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireSetSummaryEntry".
 */
export type WireSetSummaryEntry = WireTextGoalLogEntry & {
  /**
   * Entry type: set summary (SET_SUMMARY_ENTRY_TYPE in Dart)
   */
  t: "su";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireClearSummaryEntry".
 */
export type WireClearSummaryEntry = WireGoalLogEntry & {
  /**
   * Entry type: clear summary (CLEAR_SUMMARY_ENTRY_TYPE in Dart)
   */
  t: "cSu";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireArchiveNoteLogEntry".
 */
export type WireArchiveNoteLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: archive note (ARCHIVE_NOTE_ENTRY_TYPE in Dart)
   */
  t: "aN";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireSetParentLogEntry".
 */
export type WireSetParentLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: set parent (SET_PARENT_ENTRY_TYPE in Dart)
   */
  t: "sP";
  /**
   * Id of the parent goal (SetParentLogEntry.parentId in Dart)
   */
  pI?: string | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireMakeAnchorLogEntry".
 */
export type WireMakeAnchorLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: make anchor (MAKE_ANCHOR_ENTRY_TYPE in Dart)
   */
  t: "mA";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireClearAnchorLogEntry".
 */
export type WireClearAnchorLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: clear anchor (CLEAR_ANCHOR_ENTRY_TYPE in Dart)
   */
  t: "cA";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireAddParentLogEntry".
 */
export type WireAddParentLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: add parent (ADD_PARENT_ENTRY_TYPE in Dart)
   */
  t: "aP";
  /**
   * Id of the parent goal (AddParentLogEntry.parentId in Dart)
   */
  pI: string;
  /**
   * Whether this is a slice (AddParentLogEntry.isSlice in Dart)
   */
  iS?: boolean;
  /**
   * Displayed child path (AddParentLogEntry.displayedChildPath in Dart)
   */
  dCP?: string[];
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireCreateInstanceLogEntry".
 */
export type WireCreateInstanceLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: create instance (CREATE_INSTANCE_ENTRY_TYPE in Dart)
   */
  t: "cI";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireRemoveParentLogEntry".
 */
export type WireRemoveParentLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: remove parent (REMOVE_PARENT_ENTRY_TYPE in Dart)
   */
  t: "rP";
  /**
   * Id of the parent goal (RemoveParentLogEntry.parentId in Dart)
   */
  pI: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireStatusLogEntry".
 */
export type WireStatusLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: status (STATUS_ENTRY_TYPE in Dart)
   */
  t: "s";
  /**
   * Status value (StatusLogEntry.status in Dart)
   */
  s?: string | null;
  /**
   * Start time as integer timestamp (StatusLogEntry.startTime in Dart)
   */
  sT?: number | null;
  /**
   * End time as integer timestamp (StatusLogEntry.endTime in Dart)
   */
  eT?: number | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireArchiveStatusLogEntry".
 */
export type WireArchiveStatusLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: archive status (ARCHIVE_STATUS_ENTRY_TYPE in Dart)
   */
  t: "aS";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireClearStatusLogEntry".
 */
export type WireClearStatusLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: clear status (CLEAR_STATUS_ENTRY_TYPE in Dart)
   */
  t: "cS";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireAddStatusIntentionLogEntry".
 */
export type WireAddStatusIntentionLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: add status intention (ADD_STATUS_INTENTION_ENTRY_TYPE in Dart)
   */
  t: "aSI";
  /**
   * Intention text (AddStatusIntentionLogEntry.intentionText in Dart)
   */
  iT: string;
  /**
   * Id of the StatusLogEntry this is being added to (AddStatusIntentionLogEntry.statusId in Dart)
   */
  sI: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireAddStatusReflectionLogEntry".
 */
export type WireAddStatusReflectionLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: add status reflection (ADD_STATUS_REFLECTION_ENTRY_TYPE in Dart)
   */
  t: "aSR";
  /**
   * Reflection text (AddStatusReflectionLogEntry.reflectionText in Dart)
   */
  rT: string;
  /**
   * Id of the StatusLogEntry this is being added to (AddStatusReflectionLogEntry.statusId in Dart)
   */
  sI: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireParentContextCommentEntry".
 */
export type WireParentContextCommentEntry = WireTextGoalLogEntry & {
  /**
   * Entry type: parent context comment (PARENT_CONTEXT_COMMENT_ENTRY_TYPE in Dart)
   */
  t: "pCC";
  /**
   * Id of the parent goal (ParentContextCommentEntry.parentId in Dart)
   */
  pI: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireDocumentContentsLogEntry".
 */
export type WireDocumentContentsLogEntry = WireTextGoalLogEntry & {
  /**
   * Entry type: document contents (DOCUMENT_CONTENTS_ENTRY_TYPE in Dart)
   */
  t: "d";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireClearDocumentContentsLogEntry".
 */
export type WireClearDocumentContentsLogEntry = WireGoalLogEntry & {
  /**
   * Entry type: clear document contents (CLEAR_DOCUMENT_CONTENTS_ENTRY_TYPE in Dart)
   */
  t: "cD";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireCourseMetadataLogEntry".
 */
export type WireCourseMetadataLogEntry = WireGoalLogEntry & {
  t: "cM";
  tGI: string[];
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireReadingAssignmentLogEntry".
 */
export type WireReadingAssignmentLogEntry = WireGoalLogEntry & {
  t: "rA";
  tGI: string;
  sP: number;
  eP: number;
  sPF?: "arabic" | "roman";
  ePF?: "arabic" | "roman";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireSyllabusParseResultLogEntry".
 */
export type WireSyllabusParseResultLogEntry = WireGoalLogEntry & {
  t: "sPR";
  cfGI: string;
  tGI: string;
  cM: WireClassMapping[];
  aF: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireLongRunningOperationEntry".
 */
export type WireLongRunningOperationEntry = WireGoalLogEntry & {
  /**
   * Entry type: long running operation (LONG_RUNNING_OPERATION_ENTRY_TYPE in Dart)
   */
  t: "lRO";
  /**
   * Shared operation ID for all entries of this operation (LongRunningOperationEntry.operationId in Dart)
   */
  oId: string;
  /**
   * Type of operation (LongRunningOperationEntry.operationType in Dart)
   */
  oT: string;
  /**
   * Status of the operation: p=pending, r=running, c=completed, f=failed (LongRunningOperationEntry.status in Dart)
   */
  s: "p" | "r" | "c" | "f";
  /**
   * Error message if status is failed (LongRunningOperationEntry.errorMessage in Dart)
   */
  eM?: string | null;
  /**
   * Result data metadata (LongRunningOperationEntry.resultData in Dart)
   */
  rD?: {} | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireDeltaOp".
 */
export type WireDeltaOp = WireOp & {
  /**
   * Op type: delta (DELTA_OP_TYPE in Dart)
   */
  t: "d";
  d: WireGoalDelta;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireDisableOp".
 */
export type WireDisableOp = WireOp & {
  /**
   * Op type: disable (DISABLE_OP_TYPE in Dart)
   */
  t: "dO";
  /**
   * Id of the op being disabled (DisableOp.opId in Dart)
   */
  oI: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireEnableOp".
 */
export type WireEnableOp = WireOp & {
  /**
   * Op type: enable (ENABLE_OP_TYPE in Dart)
   */
  t: "eO";
  /**
   * Id of the op being enabled (EnableOp.opId in Dart)
   */
  oI: string;
};

export interface OpSchema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireGoalLogEntry".
 */
export interface WireGoalLogEntry {
  /**
   * The unique id of the log entry (GoalLogEntry.id in Dart)
   */
  i: string;
  /**
   * Creation time as an integer timestamp (GoalLogEntry.creationTime in Dart)
   */
  cT: number;
  /**
   * Full path to this note including the id of the note itself (GoalLogEntry.path in Dart)
   */
  p?: string[];
}
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireClassMapping".
 */
export interface WireClassMapping {
  cN: number;
  gI: string;
  d?: string;
  tp: string;
}
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireOp".
 */
export interface WireOp {
  /**
   * HLC timestamp (Op.hlcTimestamp in Dart)
   */
  h: string;
  /**
   * Unique id of the op (Op.id in Dart)
   */
  i: string;
  /**
   * Version of the op (Op.version in Dart)
   */
  v: number;
  /**
   * Type of the op (OpType, Op.TYPE_JSON_KEY in Dart)
   */
  t: string;
}
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "WireGoalDelta".
 */
export interface WireGoalDelta {
  /**
   * Id of the goal (GoalDelta.id in Dart)
   */
  i: string;
  /**
   * Text of the goal (GoalDelta.text in Dart)
   */
  t?: string | null;
  lE?: WireGoalLogEntry;
}
