/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "TextGoalLogEntry".
 */
export type TextGoalLogEntry = GoalLogEntry & {
  /**
   * Text content of the entry (TextGoalLogEntry.text in Dart)
   */
  te?: string | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "PriorityLogEntry".
 */
export type PriorityLogEntry = GoalLogEntry & {
  /**
   * Entry type: priority (PRIORITY_ENTRY_TYPE in Dart)
   */
  t: "p";
  /**
   * Priority value (PriorityLogEntry.priority in Dart)
   */
  pr?: number | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "NoteLogEntry".
 */
export type NoteLogEntry = TextGoalLogEntry & {
  /**
   * Entry type: note (NOTE_ENTRY_TYPE in Dart)
   */
  t: "n";
  /**
   * Id of the note entry being updated, if any (NoteLogEntry.updateNoteEntryId in Dart)
   */
  u?: string | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "SetSummaryEntry".
 */
export type SetSummaryEntry = TextGoalLogEntry & {
  /**
   * Entry type: set summary (SET_SUMMARY_ENTRY_TYPE in Dart)
   */
  t: "su";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "ClearSummaryEntry".
 */
export type ClearSummaryEntry = GoalLogEntry & {
  /**
   * Entry type: clear summary (CLEAR_SUMMARY_ENTRY_TYPE in Dart)
   */
  t: "cSu";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "ArchiveNoteLogEntry".
 */
export type ArchiveNoteLogEntry = GoalLogEntry & {
  /**
   * Entry type: archive note (ARCHIVE_NOTE_ENTRY_TYPE in Dart)
   */
  t: "aN";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "SetParentLogEntry".
 */
export type SetParentLogEntry = GoalLogEntry & {
  /**
   * Entry type: set parent (SET_PARENT_ENTRY_TYPE in Dart)
   */
  t: "sP";
  /**
   * Id of the parent goal (SetParentLogEntry.parentId in Dart)
   */
  pI?: string | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "MakeAnchorLogEntry".
 */
export type MakeAnchorLogEntry = GoalLogEntry & {
  /**
   * Entry type: make anchor (MAKE_ANCHOR_ENTRY_TYPE in Dart)
   */
  t: "mA";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "ClearAnchorLogEntry".
 */
export type ClearAnchorLogEntry = GoalLogEntry & {
  /**
   * Entry type: clear anchor (CLEAR_ANCHOR_ENTRY_TYPE in Dart)
   */
  t: "cA";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "AddParentLogEntry".
 */
export type AddParentLogEntry = GoalLogEntry & {
  /**
   * Entry type: add parent (ADD_PARENT_ENTRY_TYPE in Dart)
   */
  t: "aP";
  /**
   * Id of the parent goal (AddParentLogEntry.parentId in Dart)
   */
  pI: string;
  /**
   * Whether this is a slice (AddParentLogEntry.isSlice in Dart)
   */
  iS?: boolean;
  /**
   * Displayed child path (AddParentLogEntry.displayedChildPath in Dart)
   */
  dCP?: string[];
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "CreateInstanceLogEntry".
 */
export type CreateInstanceLogEntry = GoalLogEntry & {
  /**
   * Entry type: create instance (CREATE_INSTANCE_ENTRY_TYPE in Dart)
   */
  t: "cI";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "RemoveParentLogEntry".
 */
export type RemoveParentLogEntry = GoalLogEntry & {
  /**
   * Entry type: remove parent (REMOVE_PARENT_ENTRY_TYPE in Dart)
   */
  t: "rP";
  /**
   * Id of the parent goal (RemoveParentLogEntry.parentId in Dart)
   */
  pI: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "StatusLogEntry".
 */
export type StatusLogEntry = GoalLogEntry & {
  /**
   * Entry type: status (STATUS_ENTRY_TYPE in Dart)
   */
  t: "s";
  /**
   * Status value (StatusLogEntry.status in Dart)
   */
  s?: string | null;
  /**
   * Start time as integer timestamp (StatusLogEntry.startTime in Dart)
   */
  sT?: number | null;
  /**
   * End time as integer timestamp (StatusLogEntry.endTime in Dart)
   */
  eT?: number | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "ArchiveStatusLogEntry".
 */
export type ArchiveStatusLogEntry = GoalLogEntry & {
  /**
   * Entry type: archive status (ARCHIVE_STATUS_ENTRY_TYPE in Dart)
   */
  t: "aS";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "ClearStatusLogEntry".
 */
export type ClearStatusLogEntry = GoalLogEntry & {
  /**
   * Entry type: clear status (CLEAR_STATUS_ENTRY_TYPE in Dart)
   */
  t: "cS";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "AddStatusIntentionLogEntry".
 */
export type AddStatusIntentionLogEntry = GoalLogEntry & {
  /**
   * Entry type: add status intention (ADD_STATUS_INTENTION_ENTRY_TYPE in Dart)
   */
  t: "aSI";
  /**
   * Intention text (AddStatusIntentionLogEntry.intentionText in Dart)
   */
  iT: string;
  /**
   * Id of the StatusLogEntry this is being added to (AddStatusIntentionLogEntry.statusId in Dart)
   */
  sI: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "AddStatusReflectionLogEntry".
 */
export type AddStatusReflectionLogEntry = GoalLogEntry & {
  /**
   * Entry type: add status reflection (ADD_STATUS_REFLECTION_ENTRY_TYPE in Dart)
   */
  t: "aSR";
  /**
   * Reflection text (AddStatusReflectionLogEntry.reflectionText in Dart)
   */
  rT: string;
  /**
   * Id of the StatusLogEntry this is being added to (AddStatusReflectionLogEntry.statusId in Dart)
   */
  sI: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "ParentContextCommentEntry".
 */
export type ParentContextCommentEntry = TextGoalLogEntry & {
  /**
   * Entry type: parent context comment (PARENT_CONTEXT_COMMENT_ENTRY_TYPE in Dart)
   */
  t: "pCC";
  /**
   * Id of the parent goal (ParentContextCommentEntry.parentId in Dart)
   */
  pI: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "DocumentContentsEntry".
 */
export type DocumentContentsEntry = TextGoalLogEntry & {
  /**
   * Entry type: document contents (DOCUMENT_CONTENTS_ENTRY_TYPE in Dart)
   */
  t: "d";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "ClearDocumentContentsEntry".
 */
export type ClearDocumentContentsEntry = GoalLogEntry & {
  /**
   * Entry type: clear document contents (CLEAR_DOCUMENT_CONTENTS_ENTRY_TYPE in Dart)
   */
  t: "cD";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "CourseMetadataLogEntry".
 */
export type CourseMetadataLogEntry = GoalLogEntry & {
  t: "cM";
  tGI: string[];
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "ReadingAssignmentLogEntry".
 */
export type ReadingAssignmentLogEntry = GoalLogEntry & {
  t: "rA";
  tGI: string;
  sP: number;
  eP: number;
  sPF?: "arabic" | "roman";
  ePF?: "arabic" | "roman";
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "SyllabusParseResultLogEntry".
 */
export type SyllabusParseResultLogEntry = GoalLogEntry & {
  t: "sPR";
  cfGI: string;
  tGI: string;
  cM: ClassMapping[];
  aF: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "LongRunningOperationEntry".
 */
export type LongRunningOperationEntry = GoalLogEntry & {
  /**
   * Entry type: long running operation (LONG_RUNNING_OPERATION_ENTRY_TYPE in Dart)
   */
  t: "lRO";
  /**
   * Shared operation ID for all entries of this operation (LongRunningOperationEntry.operationId in Dart)
   */
  oId: string;
  /**
   * Type of operation (LongRunningOperationEntry.operationType in Dart)
   */
  oT: string;
  /**
   * Status of the operation: p=pending, r=running, c=completed, f=failed (LongRunningOperationEntry.status in Dart)
   */
  s: "p" | "r" | "c" | "f";
  /**
   * Error message if status is failed (LongRunningOperationEntry.errorMessage in Dart)
   */
  eM?: string | null;
  /**
   * Result data metadata (LongRunningOperationEntry.resultData in Dart)
   */
  rD?: {} | null;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "DeltaOp".
 */
export type DeltaOp = Op & {
  /**
   * Op type: delta (DELTA_OP_TYPE in Dart)
   */
  t: "d";
  d: GoalDelta1;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "DisableOp".
 */
export type DisableOp = Op & {
  /**
   * Op type: disable (DISABLE_OP_TYPE in Dart)
   */
  t: "dO";
  /**
   * Id of the op being disabled (DisableOp.opId in Dart)
   */
  oI: string;
};
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "EnableOp".
 */
export type EnableOp = Op & {
  /**
   * Op type: enable (ENABLE_OP_TYPE in Dart)
   */
  t: "eO";
  /**
   * Id of the op being enabled (EnableOp.opId in Dart)
   */
  oI: string;
};

export interface OpSchema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "GoalLogEntry".
 */
export interface GoalLogEntry {
  /**
   * The unique id of the log entry (GoalLogEntry.id in Dart)
   */
  i: string;
  /**
   * Creation time as an integer timestamp (GoalLogEntry.creationTime in Dart)
   */
  cT: number;
  /**
   * Full path to this note including the id of the note itself (GoalLogEntry.path in Dart)
   */
  p?: string[];
}
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "ClassMapping".
 */
export interface ClassMapping {
  cN: number;
  gI: string;
  d?: string;
  tp: string;
}
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "Op".
 */
export interface Op {
  /**
   * HLC timestamp (Op.hlcTimestamp in Dart)
   */
  h: string;
  /**
   * Unique id of the op (Op.id in Dart)
   */
  i: string;
  /**
   * Version of the op (Op.version in Dart)
   */
  v: number;
  /**
   * Type of the op (OpType, Op.TYPE_JSON_KEY in Dart)
   */
  t: string;
}
/**
 * This interface was referenced by `OpSchema`'s JSON-Schema
 * via the `definition` "GoalDelta".
 */
export interface GoalDelta {
  /**
   * Id of the goal (GoalDelta.id in Dart)
   */
  i: string;
  /**
   * Text of the goal (GoalDelta.text in Dart)
   */
  t?: string | null;
  lE?: GoalLogEntry1;
}
/**
 * Log entry for the goal (GoalDelta.logEntry in Dart)
 */
export interface GoalLogEntry1 {
  /**
   * The unique id of the log entry (GoalLogEntry.id in Dart)
   */
  i: string;
  /**
   * Creation time as an integer timestamp (GoalLogEntry.creationTime in Dart)
   */
  cT: number;
  /**
   * Full path to this note including the id of the note itself (GoalLogEntry.path in Dart)
   */
  p?: string[];
}
/**
 * Goal delta (DeltaOp.delta in Dart)
 */
export interface GoalDelta1 {
  /**
   * Id of the goal (GoalDelta.id in Dart)
   */
  i: string;
  /**
   * Text of the goal (GoalDelta.text in Dart)
   */
  t?: string | null;
  lE?: GoalLogEntry1;
}
